### ISSUE TITLE
Support further operating systems.

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/mlonmcu#30]
As a long-term goal it would be great to support operating systems different from Ubuntu/Debian. As there will definitely be dependencies which are not available on very OS, we will likely have to disable certain features/targets/... on some hosts.

## Tasks

- [x] Provide support using `--docker` command line flag
- [ ] Support latest MacOS (with limited functionality)
- [ ] ~~Check out if Windows support would be feasible (using MinGW?) -> If not, just recommend WSL2!~~
- [ ] Test and document other GNU/UNIX distributions with different package managers etc.
